name: 'pre-release'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.2
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
    - name: Setup MSBuild ExtensionPack
      run: choco install msbuild.extensionpack --version=4.0.15.0 -y      
      
    - name: Restore Application packages
      run: nuget restore Desktop\Application\MaxMix.sln
    - name: Build Application
      run: msbuild Desktop\Build.msbuild -p:SolutionDir=Application -p:Version=0.0.0.0 -p:Configuration=Debug -p:Platform="Any CPU"

    - name: Restore DriverInstaller packages
      run: nuget restore Desktop\DriverInstaller\DriverInstaller.sln
    - name: Build DriverInstaller
      run: msbuild Desktop\Build.msbuild -p:SolutionDir=DriverInstaller -p:Version=0.0.0.0 -p:Configuration=Debug -p:Platform="Any CPU"

    - name: Restore FirmwareInstaller packages
      run: nuget restore Desktop\FirmwareInstaller\FirmwareInstaller.sln
    - name: Build FirmwareInstaller
      run: msbuild Desktop\Build.msbuild -p:SolutionDir=FirmwareInstaller -p:Version=0.0.0.0 -p:Configuration=Debug -p:Platform="Any CPU"

    - name: Setup Advanced Installer
      run: choco install advanced-installer --version=17.1.1 -y
    - name: Add Advanced Installer to path
      run: echo ::add-path::"C:/Program Files (x86)/Caphyon/Advanced Installer 17.1.1/bin/x86"
    - name: Register Advanced Installer
      run: AdvancedInstaller.com /register ${{secrets.ADVANCEDINSTALLER_LICENSE}}
      
    - name: Build Installer
      run: AdvancedInstaller.com /build Desktop\Installer\Maxmix.aip

    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        path: Desktop\Installer\Builds\

    
