name: 'tests'

on:
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.2
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
     
    - name: Restore Application packages
      run: nuget restore Desktop\Application\MaxMix.sln
    - name: Build Application
      run: msbuild Desktop\Build.msbuild /p:SolutionDir=Desktop\Application\;Version=0.0.0.0;Configuration=Debug

    - name: Restore DriverInstaller packages
      run: nuget restore Desktop\DriverInstaller\DriverInstaller.sln
    - name: Build DriverInstaller
      run: msbuild Desktop\Build.msbuild /p:SolutionDir=Desktop\DriverInstaller\;Version=0.0.0.0;Configuration=Debug

    - name: Restore FirmwareInstaller packages
      run: nuget restore Desktop\FirmwareInstaller\FirmwareInstaller.sln
    - name: Build FirmwareInstaller
      run: msbuild Desktop\Build.msbuild /p:SolutionDir=Desktop\FirmwareInstaller\;Version=0.0.0.0;Configuration=Debug
    
